collections:
  - name: kubernetes.core
    version: 5.2.0
  - name: openstack.cloud
    version: 2.4.1
  - name: amazon.aws
    version: 9.4.0
  - name: community.general
    version: 10.5.0
  - name: ansible.utils
    version: 5.1.2
  - name: ansible.platform
    version: "2.5.20250326"
  - name: ansible.hub
    version: "1.0.0"
  - name: ansible.controller
    version: "4.6.11"
  - name: ansible.eda
    version: "2.8.2"
  - name: infra.aap_configuration
    version: "3.4.1"
