collections:
  - name: kubernetes.core
    version: 5.2.0
  - name: openstack.cloud
    version: 2.4.1
  - name: amazon.aws
    version: 9.4.0
  - name: community.general
    version: 10.5.0
  - name: ansible.utils
    version: 5.1.2
  - name: "cloudkit.config_as_code"
    source: "collections/ansible_collections/cloudkit/config_as_code"
    type: dir
