apiVersion: v1
kind: Secret
metadata:
  name: cluster-fulfillment-ig
type: Opaque
data:
  # Base64-encodedAWS credentials
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""

  # Base64-encoded Netris credentials
  NETRIS_PASSWORD: ""

  # Base64-encoded private key used to SSH into bare-metal servers via the bastion
  # Generate with: cat ~/.ssh/id_rsa | base64 -w0
  SERVER_SSH_KEY: ""
  # Base64-encoded private key used to SSH into the bastion host
  # Generate with: cat ~/.ssh/id_ed25519 | base64 -w0
  SERVER_SSH_BASTION_KEY: ""
