---
- name: Create server cluster
  when: server_cluster_state == 'present'
  ansible.builtin.include_tasks: create.yaml

- name: Delete server cluster
  when: server_cluster_state == 'absent'
  ansible.builtin.include_tasks: delete.yaml
