---
title: OpenStack Neutron Network Implementation
description: >
  Provisions networking resources using OpenStack Neutron

template_type: network

# NetworkClass registration fields
implementation_strategy: openstack
capabilities:
  supports_ipv4: true
  supports_ipv6: true
  supports_dual_stack: true
