---
- name: Build template spec base
  ansible.builtin.set_fact:
    vm_template_spec:
      domain:
        cpu:
          cores: "{{ vm_cpu_cores }}"
        memory:
          guest: "{{ vm_memory }}"
        devices:
          disks:
            - name: root-disk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
          rng: {}
        features:
          smm:
            enabled: true
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            vapic: {}
            spinlocks:
              spinlocks: 8191
      networks:
        - name: default
          pod: {}
      volumes:
        - name: root-disk
          dataVolume:
            name: "{{ compute_instance_name }}-root-disk"
