- name: Get InfraEnv information
  kubernetes.core.k8s_info:
    kind: InfraEnv
    api_version: agent-install.openshift.io/v1beta1
    namespace: "{{ manage_agents_agent_namespace }}"
    name: "{{ manage_agents_infraenv_name }}"
  register: infraenv

- name: Set discovery_url
  ansible.builtin.set_fact:
    discovery_url: "{{ infraenv.resources[0].status.isoDownloadURL }}"
  when: not discovery_url|default(false)

- name: Set bare metal pool template parameters
  ansible.builtin.set_fact:
    bare_metal_pool_template_parameters:
      agentPrivateNetwork: "{{ manage_agents_idle_agents_network_name }}"
      imageURL: "{{ discovery_url }}"

- name: Create bare metal pool for agent provisioning
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: osac.openshift.io/v1alpha1
      kind: BareMetalPool
      metadata:
        name: "{{ manage_agents_provisioning_pool_name }}"
        namespace: "{{ manage_agents_namespace }}"
      spec:
        hostSets: "{{ manage_agents_host_sets }}"
        profile:
          name: "{{ manage_agents_provisioning_profile }}"
          templateParameters: "{{ bare_metal_pool_template_parameters | to_json }}"

- name: Wait for bare metal pool to be ready
  kubernetes.core.k8s_info:
    kind: BareMetalPool
    api_version: osac.openshift.io/v1alpha1
    namespace: "{{ manage_agents_namespace }}"
    name: "{{ manage_agents_provisioning_pool_name }}"
  register: bmp_result
  until: >
    bmp_result.resources | length > 0 and
    bmp_result.resources[0].status is defined and
    bmp_result.resources[0].status.phase | default('') == "Ready"
  retries: 120
  delay: 15

- name: Delete bare metal pool for agent provisioning
  kubernetes.core.k8s:
    state: absent
    api_version: osac.openshift.io/v1alpha1
    kind: BareMetalPool
    name: "{{ manage_agents_provisioning_pool_name }}"
    namespace: "{{ manage_agents_namespace }}"
