- name: Destroy floating ips
  ansible.builtin.include_role:
    name: massopencloud.esi.floating_ip
    tasks_from: destroy_floating_ip.yaml
  vars:
    floating_ip_name: "{{ item }}"
  loop:
    - "{{ external_access_name }}-api"
    - "{{ external_access_name }}-ingress"

- name: Delete dns records
  ansible.builtin.include_role:
    name: dns.api.dns
    tasks_from: delete
  vars:
    dns_zone: "{{ external_access_base_domain }}"
    dns_record_name: "{{ item }}"
    dns_record_type: A
  loop:
    - "api.{{ external_access_name }}.{{ external_access_base_domain }}"
    - "api-int.{{ external_access_name }}.{{ external_access_base_domain }}"
    - "*.apps.{{ external_access_name }}.{{ external_access_base_domain }}"
