- name: Get list of existing NetworkClass resources
  ansible.builtin.uri:
    url: "{{ publish_templates_network_class_api_endpoint }}"
    validate_certs: "{{ publish_templates_validate_certs | default(true) | bool }}"
    headers:
      authorization: Bearer {{ osac_fulfillment_service_token }}
  register: network_class_check

- name: Create list of existing NetworkClass IDs
  ansible.builtin.set_fact:
    network_class_ids: >-
      {{
      network_class_check | json_query("json.items[].id")
      }}
  when: network_class_check is success and (network_class_check.json.size | default(0)) > 0

- name: Update existing NetworkClass
  loop: "{{ osac_network_classes }}"
  loop_control:
    label: "{{ network_class.id }}"
    loop_var: network_class
  when: network_class_ids is defined and network_class.id in network_class_ids
  ansible.builtin.uri:
    url: "{{ publish_templates_network_class_api_endpoint }}/{{ network_class.id }}"
    validate_certs: "{{ publish_templates_validate_certs | default(true) | bool }}"
    method: PATCH
    headers:
      authorization: Bearer {{ osac_fulfillment_service_token }}
    body_format: json
    body: "{{ network_class }}"

- name: Create new NetworkClass
  loop: "{{ osac_network_classes }}"
  loop_control:
    label: "{{ network_class.id }}"
    loop_var: network_class
  when: network_class_ids is not defined or network_class.id not in network_class_ids
  ansible.builtin.uri:
    url: "{{ publish_templates_network_class_api_endpoint }}"
    validate_certs: "{{ publish_templates_validate_certs | default(true) | bool }}"
    method: POST
    headers:
      authorization: Bearer {{ osac_fulfillment_service_token }}
    body_format: json
    body: "{{ network_class }}"
