- name: Get list of existing NetworkClass resources
  ansible.builtin.uri:
    url: "{{ publish_templates_network_class_api_endpoint }}"
    validate_certs: "{{ publish_templates_validate_certs | default(true) | bool }}"
    headers:
      authorization: Bearer {{ osac_fulfillment_service_token }}
  register: publish_templates_network_class_check

- name: Build map of existing NetworkClass implementation_strategy to IDs
  ansible.builtin.set_fact:
    publish_templates_network_class_strategy_to_id: >-
      {{
      publish_templates_network_class_strategy_to_id | default({}) | combine({item.implementation_strategy: item.id})
      }}
  loop: "{{ publish_templates_network_class_check.json.get('items', []) }}"
  when: publish_templates_network_class_check is success and item.implementation_strategy is defined

- name: Update existing NetworkClass
  loop: "{{ osac_network_classes }}"
  loop_control:
    label: "{{ network_class.implementation_strategy }}"
    loop_var: network_class
  when: >-
    publish_templates_network_class_strategy_to_id is defined and
    network_class.implementation_strategy in publish_templates_network_class_strategy_to_id
  ansible.builtin.uri:
    url: "{{ publish_templates_network_class_api_endpoint }}/{{ publish_templates_network_class_strategy_to_id[network_class.implementation_strategy] }}"
    validate_certs: "{{ publish_templates_validate_certs | default(true) | bool }}"
    method: PATCH
    headers:
      authorization: Bearer {{ osac_fulfillment_service_token }}
    body_format: json
    body: "{{ network_class }}"

- name: Create new NetworkClass
  loop: "{{ osac_network_classes }}"
  loop_control:
    label: "{{ network_class.implementation_strategy }}"
    loop_var: network_class
  when: >-
    publish_templates_network_class_strategy_to_id is not defined or
    network_class.implementation_strategy not in publish_templates_network_class_strategy_to_id
  ansible.builtin.uri:
    url: "{{ publish_templates_network_class_api_endpoint }}"
    validate_certs: "{{ publish_templates_validate_certs | default(true) | bool }}"
    method: POST
    headers:
      authorization: Bearer {{ osac_fulfillment_service_token }}
    body_format: json
    body: "{{ network_class }}"
