- name: Delete BareMetalPool
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: osac.openshift.io/v1alpha1
      kind: BareMetalPool
      metadata:
        name: "{{ cluster_infra_name }}"
        namespace: "{{ lookup('env', 'POD_NAMESPACE') }}"
        labels: "{{ {cluster_order_label: cluster_infra_name} }}"
