# To apply:
# kubectl apply -f samples/import_agents_bmc_secrets.yml

---
apiVersion: v1
kind: Secret
metadata:
  name: ostest-extraworker-0-bmc-secret
  namespace: hardware-inventory
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: ostest-extraworker-1-bmc-secret
  namespace: hardware-inventory
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: ostest-extraworker-2-bmc-secret
  namespace: hardware-inventory
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
