- name: Create Secret resource containing pull-secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "pullsecret-cluster-{{ hosted_cluster_name }}"
        namespace: "{{ hosted_cluster_namespace }}"
        labels: "{{ hosted_cluster_default_cluster_order_label }}"
      data:
        .dockerconfigjson: "{{ hosted_cluster_settings.pull_secret | to_json | b64encode }}"
      type: kubernetes.io/dockerconfigjson
  no_log: true

- name: Create Secret resource containing ssh public key
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "sshkey-cluster-{{ hosted_cluster_name }}"
        namespace: "{{ hosted_cluster_namespace }}"
        labels: "{{ hosted_cluster_default_cluster_order_label }}"
      data:
        id_rsa.pub: "{{ hosted_cluster_settings.ssh_public_key | b64encode }}"

- name: Create HostedCluster resource
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: hypershift.openshift.io/v1beta1
      kind: HostedCluster
      metadata:
        name: "{{ hosted_cluster_name }}"
        namespace: "{{ hosted_cluster_namespace }}"
        labels: "{{ {'cluster.open-cluster-management.io/clusterset': 'default'} | combine(hosted_cluster_default_cluster_order_label) }}"
      spec:
        release:
          image: "{{ ocp_release_image }}"
        pullSecret:
          name: "pullsecret-cluster-{{ hosted_cluster_name }}"
        sshKey:
          name: "sshkey-cluster-{{ hosted_cluster_name }}"
        networking:
          clusterNetwork:
            - cidr: 10.132.0.0/14
          serviceNetwork:
            - cidr: 172.31.0.0/16
        platform:
          type: Agent
          agent:
            agentNamespace: "{{ hosted_cluster_default_agent_namespace }}"
        dns:
          baseDomain: "{{ hosted_cluster_base_domain }}"
        infraID: "{{ hosted_cluster_name }}"
        services:
          - service: APIServer
            servicePublishingStrategy:
              type: LoadBalancer
              loadBalancer:
                hostname: "api.{{ hosted_cluster_name }}.{{ hosted_cluster_base_domain }}"
          - service: OAuthServer
            servicePublishingStrategy:
              type: Route
          - service: OIDC
            servicePublishingStrategy:
              type: Route
          - service: Konnectivity
            servicePublishingStrategy:
              type: Route
          - service: Ignition
            servicePublishingStrategy:
              type: Route
        controllerAvailabilityPolicy: HighlyAvailable
        infrastructureAvailabilityPolicy: HighlyAvailable
        olmCatalogPlacement: management

- name: Create NodePool resources
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: hypershift.openshift.io/v1beta1
      kind: NodePool
      metadata:
        name: "nodepool-{{ hosted_cluster_name }}-{{ item.resourceClass }}"
        namespace: "{{ hosted_cluster_namespace }}"
        labels: "{{ {esi_agent_resource_class_label: item.resourceClass} | combine(hosted_cluster_default_cluster_order_label) }}"
      spec:
        clusterName: "{{ hosted_cluster_name }}"
        replicas: "{{ item.numberOfNodes | int }}"
        management:
          autoRepair: false
          upgradeType: InPlace
        platform:
          type: Agent
          agent:
            agentLabelSelector:
              matchLabels: "{{ {esi_agent_resource_class_label: item.resourceClass} | combine(hosted_cluster_default_cluster_order_label) }}"
        release:
          image: "{{ ocp_release_image }}"
  loop: "{{ hosted_cluster_node_requests }}"
  loop_control:
    label: "Create NodePool nodepool-{{ hosted_cluster_name }}-{{ item.resourceClass }}"
