argument_specs:
  attach_host_to_network:
    options:
      host_name:
        description: Host name
        type: "str"
        required: true
      host_network:
        description: Network name
        type: "str"
        required: true
  clean_host:
    options:
      host_name:
        description: Host name
        type: "str"
        required: true
  list_hosts:
    options:
      host_class:
        description: Host class to filter hosts by
        type: "str"
        required: false
