---
# Create Neutron subnet

- name: Extract Subnet configuration
  ansible.builtin.set_fact:
    sn_name: "{{ subnet.metadata.name }}"
    sn_ipv4_cidr: "{{ subnet.spec.ipv4Cidr | default(default_subnet_ipv4_cidr) }}"
    sn_virtual_network: "{{ subnet.spec.virtualNetwork }}"

- name: Create subnet
  openstack.cloud.subnet:
    name: "{{ sn_name }}"
    network: "{{ sn_virtual_network }}"
    cidr: "{{ sn_ipv4_cidr }}"
    dns_nameservers: "{{ default_subnet_dns_nameservers }}"
    gateway_ip: "{{ sn_ipv4_cidr | ansible.utils.ipaddr('first_usable') }}"
    allocation_pool_start: "{{ sn_ipv4_cidr | ansible.utils.nthhost(10) }}"
    allocation_pool_end: "{{ sn_ipv4_cidr | ansible.utils.nthhost(-10) }}"
  register: subnet_result

- name: Display OpenStack subnet creation result
  ansible.builtin.debug:
    msg:
      - "OpenStack subnet '{{ sn_name }}' created successfully"
      - "Resource UID: {{ subnet_result.id }}"

- name: Create router
  when: default_subnet_external_gateway
  openstack.cloud.router:
    name: "router-{{ sn_name }}"
    network: "{{ default_subnet_external_network }}"
    interfaces:
      - "{{ subnet_result.id }}"
  register: router_result

- name: Display OpenStack router creation result
  ansible.builtin.debug:
    msg:
      - "OpenStack router for subnet '{{ sn_name }}' created successfully"
      - "Resource UID: {{ subnet_result.id }}"
