---
- name: Extract Subnet configuration
  ansible.builtin.set_fact:
    sn_name: "{{ subnet.metadata.name }}"

- name: Delete network
  openstack.cloud.subnet:
    name: "{{ sn_name }}"
    state: absent

- name: Display deletion status
  ansible.builtin.debug:
    msg:
      - "Subnet '{{ sn_name }}' deletion completed"
