---
- name: Fulfillment webhook
  hosts: localhost
  execution_strategy: parallel
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Create hosted cluster
      condition: event.meta.endpoint == "create-hosted-cluster"
      action:
        run_workflow_template:
          name: "{{ job_template_prefix }}-create-hosted-cluster-workflow"
          organization: "{{ job_template_organization }}"

    - name: Delete hosted cluster
      condition: event.meta.endpoint == "delete-hosted-cluster"
      action:
        run_workflow_template:
          name: "{{ job_template_prefix }}-delete-hosted-cluster-workflow"
          organization: "{{ job_template_organization }}"

    - name: Create compute instance
      condition: event.meta.endpoint == "create-compute-instance"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-create-compute-instance"
          organization: "{{ job_template_organization }}"

    - name: Delete compute instance
      condition: event.meta.endpoint == "delete-compute-instance"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-delete-compute-instance"
          organization: "{{ job_template_organization }}"

    - name: Create host pool
      condition: event.meta.endpoint == "create-hostpool"
      action:
        run_workflow_template:
          name: "{{ job_template_prefix }}-create-hostpool-workflow"
          organization: "{{ job_template_organization }}"

    - name: Delete host pool
      condition: event.meta.endpoint == "delete-hostpool"
      action:
        run_workflow_template:
          name: "{{ job_template_prefix }}-delete-hostpool-workflow"
          organization: "{{ job_template_organization }}"
