---
- name: Fulfillment webhook
  hosts: localhost
  execution_strategy: parallel
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Create hosted cluster
      condition: event.meta.endpoint == "create-hosted-cluster"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-create-hosted-cluster"
          organization: "{{ job_template_organization }}"

    - name: Delete hosted cluster
      condition: event.meta.endpoint == "delete-hosted-cluster"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-delete-hosted-cluster"
          organization: "{{ job_template_organization }}"
